### PR TITLE
Added two new learning resources

### PR DESCRIPTION
**Pull request by AlessandroArosio**
Pluralsight (paid) and Baeldung (paid and free material)

### CODE REVIEW

**Comment by AlessandroArosio** [comment]
Hi @Anushka-codergirl ,

This is good to merge now, without conflicts

**Comment by AlessandroArosio** [comment]
@Anushka-codergirl

**Comment by AlessandroArosio** [comment]
@Anushka-codergirl good to go now

**Comment by Anushka-codergirl** [comment]
Resolve conflicts.

**Comment by AlessandroArosio** [comment]
Closing this PR as it takes days for the maintainer to review it and merge. Newer PRs are approved before this one and new conflicts arise every time.

**Pull request closed without merging**
