### PR TITLE
Added 2 websites to learn java for free

### PR DESCRIPTION
**Pull request by hryxna**
Hello there,
I added 2 new Websites to Learn Java Programming for free
review it and let know
Thanks for letting me contribute towards your repo 😄

### CODE REVIEW

**Comment by Anushka-codergirl** [comment]
Thanks, @hryxna for adding these resources. 
Please resolve conflicts.

**Comment by hryxna** [comment]
hey there @Anushka-codergirl I have resolved the issue and merged it into the repo
kindly check it. 
Thank you.
Have a good day 😄

**Comment by hryxna** [comment]
hello, there @Anushka-codergirl is something wrong with my recent resolved conflict?

**Comment by hryxna** [comment]
Hello, @Anushka-codergirl sorry was busy with other tasks just realized that I need to resolve a conflict that you mentioned 😅 .
I have resolved the conflict hoping that this time it won't create conflicts and you'll be able to merge into your repo 😄 .

**Pull request merged**
