### PR TITLE
Reverse array

### PR DESCRIPTION
**Pull request by AlessandroArosio**
Added two methods to reverse an array (using java Stream and Collections)

### CODE REVIEW

**Comment by AlessandroArosio** [comment]
Hi @Anushka-codergirl ,
I've resolved the conflicts, please let me know if there's anything else I can do for you. If everything's good, please merge it :)

**Comment by Anushka-codergirl** [comment]
Not yet

**Comment by AlessandroArosio** [comment]
@Anushka-codergirl is good again now, please merge

**Comment by Anushka-codergirl** [comment]
Please resolve conflicts.

**Comment by AlessandroArosio** [comment]
Closing this PR as it takes days for the maintainer to review it and merge. Newer PRs are approved before this one and new conflicts arise every time.

**Pull request closed without merging**
